### ISSUE TITLE
composer json not same as lock blabla

### ISSUE THREAD

**Issue by garex** [g1a/composer-test-scenarios#3]
Hi Greg,

One minor issue that bothers me a little.

After I `require` somehting, I can't then run `test2` command as of composer lock and json differs.

Here are my composer.json bottom:

```json
"config": {
		"optimize-autoloader": true,
		"sort-packages": true,
		"platform": {
			"php": "5.6"
		}
	},
	"scripts": {
		"cs": "phpcs --standard=PSR2 -n src",
		"cbf": "phpcbf --standard=PSR2 -n src",
		"unit": "phpunit --colors=always --debug",
		"fix": "php-cs-fixer fix",
		"clear-kernel-cache": "rm -rf tests/TestKernel/",
		"lint": [
			"find src -name '*.php' -print0 | xargs -0 -n1 php -l",
			"find tests -name '*.php' -print0 | xargs -0 -n1 php -l"
		],
		"test": [
			"@clear-kernel-cache",
			"@lint",
			"@unit",
			"@cs"
		],
		"test2": [
			"@composer scenario symfony2",
			"@test"
		],
		"test3": [
			"@composer scenario symfony3",
			"@test"
		],
		"test4": [
			"@composer scenario symfony4",
			"mkdir -p vendor/symfony/polyfill-php70/Resources/stubs",
			"@test"
		],
		"scenario": "scenarios/install",
		"post-update-cmd": [
			"create-scenario symfony2 'symfony/dependency-injection:^2.8' --platform-php '5.6' --no-lockfile",
			"create-scenario symfony3 'symfony/dependency-injection:^3.0' --platform-php '5.6'",
			"create-scenario symfony4 'symfony/dependency-injection:^4.0' --platform-php '7.1.3' --no-lockfile"
		]
	}

```

**Comment by greg-1-anderson** [comment]
I'm not sure what the issue is. I generally put the calls to `composer scenario` in my .travis.yml or .circleci/config.yml file, and then run my tests.

Is your issue that your tests run a `composer validate`?  Or are you saying that `@test2` fails immediately after a `composer require`?  You should probably run `composer update` after `composer require` before running test scenario tests; otherwise, your dependencies for your different scenarios will not have all of your dependencies.

**Comment by garex** [comment]
Greg, I forgot how I fixed this issue locally. But I remeber, that it required some additional steps. May be `update` or somthing other. Too much time passed already )

**Comment by greg-1-anderson** [comment]
Glad you worked it out
